### ISSUE TITLE
Chat commands can execute before hint completion

### ISSUE THREAD

**Issue by Jaeiya** [Noumenae/client#60]
Right now, when typing a chat command, the input box will detect if you're typing a command or not and give you hints as you type. If you **hit** `ENTER` or `TAB` while a hint is active, the hint will fill-in the rest of the command for you and wait for you to execute that command by **hitting** `ENTER`.

To make this process quicker, when a hint is active, the `ENTER` key could immediately execute the command instead of just filling it in.

**Comment by Aedaeum** [comment]
For now, this isn't a feature that a lot of users will be desiring.

**Comment by Jaeiya** [comment]
All basement issues will be closed from now on.
