### ISSUE TITLE
On lost connection/disconnect from server, conflicts persist

### ISSUE THREAD

**Issue by Jaeiya** [Noumenae/client#66]
Every once in awhile, when reconnecting back to the server after a disconnection or lost connection, there are some socket conflicts, which produce user-duplicates. I haven't determined if a user gets left server-side or not, but the error is initialized by the client.

**Comment by Aedaeum** [comment]
I currently can't reproduce this issue, but maybe it will crop up again at a later date.

**Comment by Jaeiya** [comment]
With updates to the v2 branch, this issue is no longer applicable.
